# -*- coding: utf-8 -*-
"""Dữ liệu mô tả API + luồng giao diện cho CUSTOMER_APP_API.csv."""

# fmt: off
ENDPOINTS = [
    # --- Hệ thống ---
    dict(stt=1, module='Hệ thống', be='', uc='UC-64', title='Kiểm tra API sống', method='GET', path='/api/health', auth='Public', status='Đã có',
         api_desc='Ping backend trước khi gọi API thật. Trả tên service và timestamp — không đọc DB, không cần đăng nhập.',
         when_call='Tùy chọn: splash hoặc màn Cài đặt / debug khi cần biết server có sống không.',
         ui_flow='Không có màn riêng cho user. Dev có thể gọi nền khi app khởi động; lỗi mạng → log, không chặn vào app.',
         after_success='Không đổi UI. Tiếp tục luồng auth bình thường.',
         repo='', screen='/ (optional)', query='', body='', response='service; timestamp', errors='200', priority='P2',
         dev_task='Tùy chọn: ApiClient.healthCheck() — không bắt buộc cho release.'),

    # --- Xác thực ---
    dict(stt=2, module='Xác thực', be='BE-001', uc='UC-01', title='Đăng ký tài khoản', method='POST', path='/api/auth/register', auth='Public', status='Đã có',
         api_desc='Tạo user Supabase Auth + bản ghi profiles (role=customer). Trả JWT accessToken và object Profile để app lưu session.',
         when_call='User bấm Đăng ký trên register_page sau khi điền email, MK (≥8), họ tên, SĐT.',
         ui_flow='1) Form validate local (email, MK, SĐT).\n2) Bấm Đăng ký → loading trên nút.\n3) Thành công: lưu token + profile → điều hướng /home hoặc thông báo “kiểm tra email” nếu bật xác thực email.\n4) Lỗi 400: SnackBar email đã tồn tại.',
         after_success='Lưu accessToken (secure storage). Cập nhật AuthCubit/session. context.go(/home) hoặc màn “xác thực email”.',
         repo='customer_auth_repository.dart → signUp()', screen='/register', query='', body='email; password; full_name; phone; role=customer', response='user; accessToken', errors='400; 422', priority='P0',
         dev_task='Map response → Profile model. Không lưu password. Handle message tiếng Việt từ BE.'),

    dict(stt=3, module='Xác thực', be='BE-003', uc='UC-02', title='Đăng nhập email/MK', method='POST', path='/api/auth/login', auth='Public', status='Đã có',
         api_desc='Xác thực Supabase, trả JWT + Profile. Chỉ customer role được vào app này.',
         when_call='login_page — bấm Đăng nhập sau nhập email + password.',
         ui_flow='1) Validate form.\n2) POST login → loading.\n3) OK: lưu session → /home.\n4) 401: “Email hoặc mật khẩu không đúng”.\n5) 403: “Vui lòng xác thực email”.',
         after_success='Persist token. Splash lần sau đọc token → GET /customers/me hoặc /auth/me.',
         repo='customer_auth_repository.dart → signIn()', screen='/login', query='', body='email; password', response='user; accessToken', errors='401; 403', priority='P0',
         dev_task='Tách lỗi 401 vs 403 cho message rõ.'),

    dict(stt=4, module='Xác thực', be='BE-004', uc='UC-02', title='Đăng nhập Google', method='POST', path='/api/auth/google', auth='Public', status='Đã có',
         api_desc='Đổi Google id_token lấy session UniMove. User mới → tạo profile từ metadata Google.',
         when_call='login_page — nút “Tiếp tục với Google” sau google_sign_in lấy id_token.',
         ui_flow='1) Mở Google picker.\n2) Có id_token → POST /auth/google.\n3) OK như login email.\n4) Hủy Google → không gọi API.',
         after_success='Giống login — /home.',
         repo='customer_auth_repository.dart + google_sign_in_service.dart', screen='/login', query='', body='id_token', response='user; accessToken', errors='401; 403', priority='P0',
         dev_task='Chỉ gửi id_token, không gửi access token OAuth khác.'),

    dict(stt=5, module='Xác thực', be='BE-003', uc='UC-02', title='Profile từ JWT', method='GET', path='/api/auth/me', auth='Bearer', status='Đã có',
         api_desc='Đọc claims JWT, trả metadata profile (không query nặng). Dùng khôi phục session nhanh.',
         when_call='splash_page khi có token local; hoặc fallback nếu GET /customers/me timeout.',
         ui_flow='Splash: có token → GET /auth/me → có user → /home; không token → /login; 401 → xóa token → /login.',
         after_success='Hydrate tên/avatar tạm trên splash nếu cần.',
         repo='customer_auth_repository.dart → getCurrentUser()', screen='/ (splash)', query='', body='', response='Profile', errors='401', priority='P0',
         dev_task='Ưu tiên GET /customers/me cho đủ field (loyalty, total_orders). /auth/me là fallback.'),

    dict(stt=6, module='Xác thực', be='BE-007', uc='UC-03', title='Quên MK — gửi OTP', method='POST', path='/api/auth/forgot-password', auth='Public', status='Đã có',
         api_desc='Kích hoạt Supabase gửi email/OTP reset. Không trả token.',
         when_call='forgot_password_page — nhập email, bấm Gửi.',
         ui_flow='1) Nhập email.\n2) POST → loading.\n3) Luôn hiện message “đã gửi hướng dẫn” (tránh lộ email tồn tại).\n4) Điều hướng /reset-password.',
         after_success='SnackBar + chuyển màn nhập OTP/MK mới.',
         repo='customer_auth_repository.dart', screen='/forgot-password', query='', body='email', response='message', errors='—', priority='P1',
         dev_task='Không báo lỗi “email không tồn tại” trên UI production.'),

    dict(stt=7, module='Xác thực', be='BE-007', uc='UC-03', title='Reset MK bằng OTP', method='POST', path='/api/auth/reset-password', auth='Public', status='Đã có',
         api_desc='Đặt MK mới với email + otp/token từ email.',
         when_call='reset_password_page — đủ email, OTP, MK mới.',
         ui_flow='1) Form 3 field.\n2) POST reset.\n3) OK → /login + SnackBar thành công.\n4) 400 OTP sai → hiện lỗi dưới ô OTP.',
         after_success='context.go(/login).',
         repo='customer_auth_repository.dart', screen='/reset-password', query='', body='email; otp/token; new_password', response='message', errors='400', priority='P1',
         dev_task='Hỗ trợ cả field otp và token theo BE.'),

    dict(stt=8, module='Xác thực', be='BE-006', uc='UC-18', title='Đổi MK đã đăng nhập', method='POST', path='/api/auth/change-password', auth='Bearer', status='Đã có',
         api_desc='Đổi MK qua Supabase với MK cũ xác minh lại.',
         when_call='change_password_page — MK cũ + MK mới + xác nhận.',
         ui_flow='1) Validate MK mới ≥8, khớp xác nhận.\n2) POST → loading.\n3) OK → SnackBar → pop.\n4) 400 MK cũ sai.',
         after_success='Navigator.pop; không logout.',
         repo='customer_auth_repository.dart', screen='/change-password', query='', body='old_password; new_password', response='message', errors='400', priority='P1',
         dev_task='Field BE có thể là current_password — map đúng contract nodejs-api.'),

    dict(stt=9, module='Xác thực', be='BE-005', uc='UC-02', title='Đăng xuất', method='POST', path='/api/auth/logout', auth='Bearer', status='Chưa có',
         api_desc='Revoke refresh token phía server (tùy triển khai). App vẫn phải xóa token local.',
         when_call='profile_page — nút Đăng xuất, confirm dialog.',
         ui_flow='1) Dialog xác nhận.\n2) POST logout (best effort) + clear storage.\n3) context.go(/login) dù API lỗi mạng.',
         after_success='Xóa hết session, reset cubit.',
         repo='customer_auth_repository.dart → signOut()', screen='/profile', query='', body='', response='message', errors='401', priority='P2',
         dev_task='signOut() luôn clear local; POST logout không chặn UX.'),

    # --- Profile ---
    dict(stt=10, module='Hồ sơ', be='BE-008', uc='UC-18', title='Xem hồ sơ', method='GET', path='/api/customers/me', auth='Bearer', status='Đã có',
         api_desc='Lấy đầy đủ profile customer: họ tên, MSSV, trường, điểm, tổng đơn, avatar… Dùng cho mọi màn cần user info.',
         when_call='Vào /profile, /home (header), sau login, sau PATCH profile.',
         ui_flow='profile_page initState → loading skeleton → hiển thị card thông tin, thống kê đơn/điểm.\nhome_page: avatar + tên từ cùng API hoặc cache.',
         after_success='setState/Cubit với Profile. Hiển thị placeholder avatar nếu null.',
         repo='customer_auth_repository.dart → fetchProfile()', screen='/profile; /home', query='', body='', response='Profile đầy đủ', errors='401', priority='P0',
         dev_task='Cache profile trong memory session; refresh khi pull-to-refresh profile.'),

    dict(stt=11, module='Hồ sơ', be='BE-009', uc='UC-18', title='Sửa hồ sơ', method='PATCH', path='/api/customers/me', auth='Bearer', status='Đã có',
         api_desc='Cập nhật một phần metadata profile. Email/role không đổi qua API này.',
         when_call='edit_profile_page — bấm Lưu.',
         ui_flow='1) Form sửa họ tên, SĐT, MSSV, trường, ngày sinh, giới tính.\n2) PATCH chỉ field dirty.\n3) OK → SnackBar “Đã lưu” → pop với kết quả true.\n4) profile_page reload GET /me.',
         after_success='Pop(true); parent gọi lại fetchProfile.',
         repo='customer_auth_repository.dart → updateProfile()', screen='/profile/edit', query='', body='full_name?; phone?; student_id?; university?; date_of_birth?; gender?', response='Profile', errors='401; 422', priority='P0',
         dev_task='Chuẩn hóa phone +84 như repository hiện có.'),

    dict(stt=12, module='Hồ sơ', be='BE-010', uc='UC-18', title='Upload avatar', method='POST', path='/api/customers/me/avatar', auth='Bearer', status='Đã có',
         api_desc='Upload ảnh lên Storage, cập nhật profiles.avatar_url, trả URL public.',
         when_call='edit_profile_page — chọn ảnh từ gallery/camera.',
         ui_flow='1) image_picker chọn file.\n2) Preview tròn trên form.\n3) POST multipart → loading overlay.\n4) OK → hiện avatar mới; home/profile đồng bộ khi quay lại.',
         after_success='Cập nhật Profile.avatar_url trong state.',
         repo='customer_auth_repository.dart → uploadAvatar()', screen='/profile/edit; /home', query='', body='multipart field avatar', response='avatar_url', errors='401; 413', priority='P0',
         dev_task='Giới hạn 2MB; compress ảnh trước upload nếu cần.'),

    dict(stt=13, module='Thanh toán/Ví', be='BE-034', uc='UC-12', title='Số dư ví', method='GET', path='/api/customers/me/wallet', auth='Bearer', status='Chưa có',
         api_desc='Trả balance ví UniMove + loyalty_points (có thể trùng field profile).',
         when_call='Mở tab Thanh toán (payments_tab_page).',
         ui_flow='Tab init → hero card “Số dư ví” + điểm thưởng.\nLỗi → hiện 0 hoặc retry.',
         after_success='Hiển thị số tiền format VND.',
         repo='payments_repository.dart → fetchWalletBalance()', screen='Tab Thanh toán', query='', body='', response='balance; currency; loyalty_points', errors='401', priority='P1',
         dev_task='Thay mock/fallback đọc loyalty_points từ profile.'),

    dict(stt=14, module='Đặt chuyến', be='BE-017', uc='UC-06', title='Địa điểm gần đây', method='GET', path='/api/customers/me/recent-places', auth='Bearer', status='Chưa có',
         api_desc='Lấy tối đa N địa chỉ pickup/delivery từ lịch sử đơn của user — gợi ý nhanh.',
         when_call='choose_location_page mở ra (loadPlaces trong BookingFlowCubit).',
         ui_flow='1) Màn có ô pickup cố định + destination.\n2) List chip/card “Gần đây” dưới ô địa chỉ.\n3) Tap item → điền subtitle vào destination, có thể set lat/lng vào state.\n4) Empty list → ẩn section.',
         after_success='BookingFlowState.destination cập nhật; user bấm Tiếp tục → validate-route.',
         repo='booking_mock_repository.dart → fetchRecentPlaces()', screen='/booking/location', query='limit=5', body='', response='RecentPlace[]', errors='401', priority='P0',
         dev_task='Model RecentPlace trong booking_models.dart — map đúng title/subtitle/lat/lng.'),

    dict(stt=15, module='Thanh toán', be='BE-036', uc='UC-12', title='DS PT thanh toán', method='GET', path='/api/customers/me/payment-methods', auth='Bearer', status='Chưa có',
         api_desc='Danh sách PayOS/MoMo/… đã liên kết (token vault, không có PAN).',
         when_call='payment_methods_page init.',
         ui_flow='List tile từng PT + badge “Mặc định”. FAB Thêm → /payments/methods/add.',
         after_success='Render list; empty → CTA liên kết PayOS/MoMo.',
         repo='payments_repository.dart', screen='/payments/methods', query='', body='', response='PaymentMethod[]', errors='401', priority='P1',
         dev_task='Thay mock_payment_methods_data.'),

    dict(stt=16, module='Thanh toán', be='BE-036', uc='UC-12', title='Thêm PT thanh toán', method='POST', path='/api/customers/me/payment-methods', auth='Bearer', status='Chưa có',
         api_desc='Lưu tham chiếu PT sau flow liên kết cổng (PayOS/MoMo).',
         when_call='Sau link_payment_method_page / add_card thành công.',
         ui_flow='1) User chọn loại PayOS/MoMo.\n2) WebView/deep link cổng (future).\n3) POST lưu token_ref.\n4) Pop về list refresh.',
         after_success='Navigator.pop; GET lại danh sách.',
         repo='payments_repository.dart', screen='/payments/methods/add', query='', body='kind; label; token_ref', response='PaymentMethod', errors='401', priority='P1',
         dev_task='Không gửi số thẻ thật lên BE.'),

    dict(stt=17, module='Thanh toán', be='BE-036', uc='UC-12', title='Đặt PT mặc định', method='PATCH', path='/api/customers/me/payment-methods/:id', auth='Bearer', status='Chưa có',
         api_desc='Đánh dấu một PT làm mặc định cho checkout.',
         when_call='Tap “Đặt mặc định” trên tile hoặc financial_settings.',
         ui_flow='PATCH → loading nhỏ trên tile → refresh list, một item is_default=true.',
         after_success='payment_page pre-select PT này.',
         repo='payments_repository.dart', screen='/payments/methods', query='', body='is_default: true', response='PaymentMethod', errors='404', priority='P1',
         dev_task=''),

    dict(stt=18, module='Thanh toán', be='BE-036', uc='UC-12', title='Xóa PT', method='DELETE', path='/api/customers/me/payment-methods/:id', auth='Bearer', status='Chưa có',
         api_desc='Xóa liên kết PT.',
         when_call='Swipe hoặc menu Xóa trên payment_methods_page.',
         ui_flow='Confirm dialog → DELETE → remove khỏi list.',
         after_success='setState bỏ item.',
         repo='payments_repository.dart', screen='/payments/methods', query='', body='', response='message', errors='404', priority='P2',
         dev_task=''),

    dict(stt=19, module='Đặt chuyến', be='BE-018', uc='UC-06', title='Validate tuyến', method='POST', path='/api/booking/validate-route', auth='Bearer', status='Chưa có',
         api_desc='Tính khoảng cách km và parse city/district cho pickup/delivery — chuẩn bị chọn gói và estimate.',
         when_call='choose_location_page — bấm Tiếp tục khi đã có pickup + destination text (và lat/lng nếu có).',
         ui_flow='1) User nhập/chọn địa chỉ.\n2) Tiếp tục → POST.\n3) OK → lưu distance + district vào BookingFlowCubit → push /booking/packages.\n4) 400 → SnackBar địa chỉ không hợp lệ.\nLuồng Pass đồ: pickup = area tin đăng, destination = nơi nhận.',
         after_success='context.push(/booking/packages) hoặc partners tùy flow.',
         repo='booking_mock_repository.dart', screen='/booking/location', query='', body='pickup_address; delivery_address; lat/lng?', response='estimated_distance_km; cities; districts', errors='400', priority='P0',
         dev_task='Gọi trước estimate-price và create order.'),

    dict(stt=20, module='Đặt chuyến', be='BE-021', uc='UC-08', title='Gói combo', method='GET', path='/api/service-packages', auth='Bearer', status='Chưa có',
         api_desc='Catalog gói Economy/Standard/Premium: giá, km kèm, phí km thêm, khuân vác kèm, features.',
         when_call='service_packages_page init.',
         ui_flow='1) Grid/list 3 card gói.\n2) Badge TIẾT KIỆM / PHỔ BIẾN.\n3) Chọn 1 → BookingFlowCubit.selectTier → Tiếp tục /booking/partners hoặc insurance.',
         after_success='State.serviceTier + movePackagePrice cập nhật.',
         repo='booking_mock_repository.dart → fetchPackages()', screen='/booking/packages', query='active=true', body='', response='ServicePackage[]', errors='401', priority='P0',
         dev_task='Map tier string ↔ ServiceTier enum trong cubit.'),

    dict(stt=21, module='Đặt chuyến', be='', uc='UC-10', title='Gói bảo hiểm', method='GET', path='/api/insurance-plans', auth='Bearer', status='Chưa có',
         api_desc='Danh mục bảo hiểm hàng hóa: mức phí, coverage, benefits.',
         when_call='insurance_selection_page init (sau chọn gói, trước payment).',
         ui_flow='1) List plan + “Không mua”.\n2) Chọn plan → state.insurancePlanId.\n3) Tiếp tục payment — estimate có insurance_fee.',
         after_success='push /booking/payment.',
         repo='booking_mock_repository.dart', screen='/booking/insurance', query='', body='', response='CargoInsurancePlan[]', errors='401', priority='P1',
         dev_task=''),

    dict(stt=22, module='Đặt chuyến', be='BE-019', uc='UC-05', title='Browse nhà xe', method='GET', path='/api/providers/browse', auth='Bearer', status='Đã có',
         api_desc='Danh sách provider đã verified: giá base, rating, loại xe, avatar.',
         when_call='choose_partner_page; home “So sánh nhà xe”.',
         ui_flow='1) List PartnerOffer card.\n2) Filter/sort (giá, rating, khoảng cách nếu có GPS).\n3) Tap chọn → highlight → Tiếp tục.\n4) Lưu provider_id vào BookingFlowState.',
         after_success='state.selectedProviderId set → insurance hoặc payment.',
         repo='providers_repository.dart → browse()', screen='/booking/partners; /home', query='city; limit; min/max_price; min_rating; sort; lat; lng; radius_km', body='', response='PartnerOffer[]', errors='401', priority='P0',
         dev_task='Map JSON profiles nested → PartnerOffer UI model.'),

    dict(stt=23, module='Đặt chuyến', be='BE-020', uc='UC-05', title='Chi tiết nhà xe', method='GET', path='/api/providers/:id', auth='Bearer', status='Chưa có',
         api_desc='Thông tin chi tiết + gói dịch vụ provider + 5 review gần nhất.',
         when_call='Optional: bottom sheet khi long-press card partner (chưa có UI — chuẩn bị).',
         ui_flow='Sheet/Page: header nhà xe, verified badge, list packages, horizontal reviews.',
         after_success='User chọn package con hoặc confirm provider.',
         repo='providers_repository.dart', screen='/booking/partners', query='', body='', response='provider; packages[]; recent_reviews[]', errors='404', priority='P1',
         dev_task=''),

    dict(stt=24, module='Đặt chuyến', be='BE-026', uc='UC-11', title='Báo giá khuân vác', method='GET', path='/api/labor/quotes', auth='Bearer', status='Chưa có',
         api_desc='Trả ≥4 báo giá đội khuân vác theo số người, giờ, phí bậc.',
         when_call='labor_configure_page sau khi nhập helper_count, hours; labor_providers_page refresh.',
         ui_flow='1) Section “Báo giá đội khuân vác”.\n2) Card quote — chọn 1 (badge Gần nhất/Rẻ nhất).\n3) Giá cộng vào BookingFlowState.laborQuotedPrice.',
         after_success='Enable nút tiếp tục payment hoặc tạo đơn labor.',
         repo='labor_repository.dart', screen='/booking/labor/*', query='helper_count; labor_hours; floor_fee; for_existing_order', body='', response='LaborProviderQuote[]', errors='401', priority='P1',
         dev_task='for_existing_order=true khi addon từ đơn đang chạy.'),

    dict(stt=25, module='Đặt chuyến', be='BE-022', uc='UC-10', title='Ước tính giá', method='POST', path='/api/booking/estimate-price', auth='Bearer', status='Chưa có',
         api_desc='Server tính breakdown: base, km, bậc, khuân vác, bảo hiểm, giảm giá, tổng, tiền cọc 30%.',
         when_call='payment_page init và mỗi khi đổi mã KM (debounce) hoặc đổi insurance/labor.',
         ui_flow='1) Màn payment hiện skeleton “Đang tính giá…”.\n2) POST với state cubit đầy đủ.\n3) Hiện bảng Chi tiết: từng dòng giá + tổng + cọc.\n4) Invalid promo → message dưới ô mã.',
         after_success='Cubit.total, depositAmount cập nhật; enable nút Đặt cọc.',
         repo='booking_mock_repository.dart', screen='/booking/payment', query='', body='service_type; vehicle_size; distance_km; floors; insurance_plan_id?; promotion_code?; pass_item_id?', response='base_price..deposit_amount', errors='400', priority='P0',
         dev_task='Đồng bộ số với POST /orders body.'),

    dict(stt=26, module='Khuyến mãi', be='BE-033', uc='UC-12', title='Validate mã KM', method='POST', path='/api/promotions/validate', auth='Bearer', status='Chưa có',
         api_desc='Kiểm tra mã UNIMOVE50… còn hiệu lực và số tiền giảm.',
         when_call='payment_page — bấm Áp dụng cạnh ô mã.',
         ui_flow='1) Nhập mã.\n2) POST với order_total hiện tại.\n3) valid=true → cập nhật discount trên UI, gọi lại estimate.\n4) valid=false → Text đỏ dưới ô.',
         after_success='Re-fetch estimate-price với promotion_code.',
         repo='booking_flow_cubit', screen='/booking/payment', query='', body='code; order_total', response='valid; discount_amount; message', errors='400', priority='P1',
         dev_task=''),

    dict(stt=27, module='Khuyến mãi', be='BE-037', uc='UC-04', title='Banner KM trang chủ', method='GET', path='/api/promotions/active', auth='Bearer', status='Chưa có',
         api_desc='Promo cards cho carousel home: title, ảnh, deep link route.',
         when_call='home_page init (section Flash sale / khuyến mãi).',
         ui_flow='1) Carousel banner.\n2) Tap → context.push(action_route) hoặc mở booking.\n3) Empty → ẩn section.',
         after_success='Điều hướng theo action_route.',
         repo='home_page (trực tiếp hoặc repo mới)', screen='/home', query='', body='', response='promo[]', errors='401', priority='P2',
         dev_task=''),

    dict(stt=28, module='Đơn hàng', be='BE-024', uc='UC-19', title='Danh sách đơn', method='GET', path='/api/orders', auth='Bearer', status='Đã có',
         api_desc='Đơn của customer, filter active/completed/status, join provider summary.',
         when_call='activity_page, orders_history_page, labor_order_picker, home shortcut đơn đang chạy.',
         ui_flow='1) Tab Hoạt động: active_only → card đơn in_progress + CTA tracking.\n2) Lịch sử: filter chip status.\n3) Tap card → /orders/:id/tracking.\n4) Pull refresh.',
         after_success='List CustomerOrder map từ JSON (order_api_mapper).',
         repo='customer_orders_repository.dart → fetchOrders()', screen='Tab Hoạt động; /orders/history', query='status; page; limit; active_only; completed_only', body='', response='Order[] + provider', errors='401', priority='P0',
         dev_task='Thay mock khi có JWT. conversationId để mở chat.'),

    dict(stt=29, module='Đơn hàng', be='BE-024', uc='UC-19', title='Chi tiết đơn', method='GET', path='/api/orders/:id', auth='Bearer', status='Đã có',
         api_desc='Một đơn + có thể kèm timeline events.',
         when_call='Tracking refresh; deep link order id.',
         ui_flow='Dùng chung data với tracking hoặc fetch riêng khi vào tracking.',
         after_success='Populate OrderTrackingPage header.',
         repo='customer_orders_repository.dart', screen='/orders/:id/tracking', query='', body='', response='Order', errors='404', priority='P0',
         dev_task=''),

    dict(stt=30, module='Đơn hàng', be='BE-023', uc='UC-11', title='Tạo đơn chuyển xe', method='POST', path='/api/orders', auth='Bearer', status='Đã có',
         api_desc='Insert orders status=pending với đầy đủ địa chỉ, giá, provider_id, pass_item_id, insurance…',
         when_call='payment_page — bấm Đặt cọc / Xác nhận: tạo đơn TRƯỚC rồi deposit.',
         ui_flow='1) User xác nhận breakdown.\n2) POST /orders → nhận order_id, order_number.\n3) Ngay sau đó POST /payments/deposit.\n4) Mở PayOS URL/QR.\n5) Thành công → /orders/:id/tracking.\nLuồng Pass: body có pass_item_id.',
         after_success='Navigate tracking; clear hoặc giữ booking state tùy product.',
         repo='customer_orders_repository.dart → createOrder()', screen='/booking/payment', query='', body='pickup_*; delivery_*; prices; provider_id; pass_item_id?; promotion_code?; labor_provider_id?', response='Order pending', errors='422', priority='P0',
         dev_task='customer_orders_repository đã có skeleton — bổ sung field thiếu.'),

    dict(stt=31, module='Đơn hàng', be='BE-027', uc='UC-11', title='Tạo đơn khuân vác', method='POST', path='/api/orders/labor', auth='Bearer', status='Chưa có',
         api_desc='Đơn chỉ khuân vác hoặc addon gắn linked_order_id.',
         when_call='payment_page isLaborService hoặc labor flow riêng.',
         ui_flow='Giống tạo đơn chuyển xe nhưng mode labor_only/labor_addon; có thể copy địa chỉ từ đơn gốc.',
         after_success='deposit → tracking.',
         repo='labor_repository.dart', screen='/booking/labor/*; payment', query='', body='mode; linked_order_id?; labor_provider_id; helper_count; hours; addresses', response='Order', errors='401', priority='P1',
         dev_task=''),

    dict(stt=32, module='Đơn hàng', be='BE-025', uc='UC-13', title='Hủy đơn', method='PATCH', path='/api/orders/:id/cancel', auth='Bearer', status='Chưa có',
         api_desc='status=cancelled + reason; trigger refund % theo platform_settings.',
         when_call='Nút Hủy trên activity/tracking (khi còn được hủy).',
         ui_flow='1) Dialog nhập lý do.\n2) PATCH.\n3) OK → card chuyển trạng thái Đã hủy; SnackBar hoàn tiền (nếu có).',
         after_success='Refresh list orders.',
         repo='customer_orders_repository.dart', screen='activity; tracking', query='', body='reason', response='Order cancelled', errors='400', priority='P1',
         dev_task=''),

    dict(stt=33, module='Đơn hàng', be='BE-031', uc='UC-13', title='Xác nhận hoàn thành', method='POST', path='/api/orders/:id/confirm-complete', auth='Bearer', status='Chưa có',
         api_desc='Khách xác nhận đã nhận hàng — giải phóng escrow cho provider.',
         when_call='tracking khi provider đã complete — nút “Xác nhận hoàn thành”.',
         ui_flow='1) Hiện nút sau bước cuối timeline.\n2) Confirm dialog.\n3) POST → timeline Đã hoàn thành.\n4) Gợi ý /orders/:id/review.',
         after_success='push review hoặc SnackBar đánh giá.',
         repo='order_tracking_page', screen='/orders/:id/tracking', query='', body='', response='Order completed', errors='400', priority='P1',
         dev_task=''),

    dict(stt=34, module='Theo dõi', be='BE-050', uc='UC-13', title='Tracking tổng hợp', method='GET', path='/api/orders/:id/tracking', auth='Bearer', status='Chưa có',
         api_desc='Một payload: order, provider contact, GPS, timeline events, conversation_id, eta.',
         when_call='order_tracking_page init + pull refresh.',
         ui_flow='1) Map ảnh/mock map + marker driver.\n2) Timeline trạng thái (pending→completed).\n3) Card tài xế: gọi tel, chat → /chat/:conversationId.\n4) ETA text “~25 phút”.',
         after_success='Render TrackingSnapshot; subscribe Realtime bổ sung.',
         repo='customer_orders_repository.dart → fetchTracking()', screen='/orders/:id/tracking', query='', body='', response='order; provider; location; events; conversation_id; eta', errors='404', priority='P0',
         dev_task='Thay mock_orders_data.trackingFor.'),

    dict(stt=35, module='Theo dõi', be='BE-053', uc='UC-13', title='ETA', method='GET', path='/api/orders/:id/eta', auth='Bearer', status='Chưa có',
         api_desc='Chỉ ETA phút — poll nhẹ hơn full tracking.',
         when_call='Optional timer 60s trên tracking page.',
         ui_flow='Cập nhật RichText ETA không reload cả trang.',
         after_success='setState eta_minutes.',
         repo='order_tracking_page', screen='/orders/:id/tracking', query='', body='', response='eta_minutes', errors='404', priority='P2',
         dev_task=''),

    dict(stt=36, module='Theo dõi', be='BE-052', uc='UC-59', title='Realtime', method='REALTIME', path='supabase:order:{orderId}', auth='Bearer', status='Chưa có',
         api_desc='Subscribe thay đổi orders.status và provider_locations — không qua REST.',
         when_call='Sau GET tracking thành công, khi màn tracking đang visible.',
         ui_flow='1) initState subscribe.\n2) On event → cập nhật marker map + timeline chip.\n3) dispose unsubscribe.',
         after_success='Animate marker; không F5.',
         repo='order_tracking_page + supabase client', screen='/orders/:id/tracking', query='', body='subscribe', response='status; lat/lng', errors='—', priority='P1',
         dev_task='Document channel name cho Flutter team.'),

    dict(stt=37, module='Đánh giá', be='BE-059', uc='UC-17', title='Gửi đánh giá', method='POST', path='/api/orders/:id/review', auth='Bearer', status='Chưa có',
         api_desc='Lưu review 1-1 order; cập nhật rating provider.',
         when_call='review_trip_page — Gửi đánh giá.',
         ui_flow='1) Chọn sao 1-5.\n2) Chip tags (Đúng giờ, Nhiệt tình…).\n3) Comment optional.\n4) POST → thank you → referral offer (GET /referrals/me).',
         after_success='pop; orders list has_review=true.',
         repo='review_trip_page', screen='/orders/:id/review', query='', body='rating; comment?; tags[]', response='review', errors='400', priority='P1',
         dev_task=''),

    dict(stt=38, module='Thanh toán', be='BE-028', uc='UC-12', title='Đặt cọc', method='POST', path='/api/payments/deposit', auth='Bearer', status='Đã có',
         api_desc='Tạo payment pending + PayOS URL/QR cho 30% tổng đơn.',
         when_call='Ngay sau POST /orders thành công trên payment_page.',
         ui_flow='1) Loading “Đang tạo thanh toán…”.\n2) Nhận payos_payment_url → url_launcher hoặc WebView.\n3) QR hiển thị trong bottom sheet (nếu có qr field).\n4) User thanh toán xong (webhook) → vào tracking.',
         after_success='context.push tracking; poll payment status optional.',
         repo='customer_orders_repository / payments_repository', screen='/booking/payment', query='', body='order_id; amount; payment_method', response='payment_url; qr; expires_at', errors='400', priority='P0',
         dev_task='Đã gọi trong customer_orders_repository — hoàn thiện UI mở PayOS.'),

    dict(stt=39, module='Thanh toán', be='BE-029', uc='UC-61', title='Webhook PayOS', method='POST', path='/api/webhooks/payos', auth='Server', status='Đã có',
         api_desc='PayOS gọi BE khi thanh toán xong → payments.completed.',
         when_call='Không từ app.',
         ui_flow='N/A — server only.',
         after_success='App biết qua refresh order hoặc push notification.',
         repo='—', screen='—', query='', body='PayOS payload', response='200', errors='—', priority='P0',
         dev_task='Flutter: optional polling GET order sau khi user quay lại từ PayOS.'),

    dict(stt=40, module='Thanh toán', be='BE-035', uc='UC-12', title='Lịch sử GD', method='GET', path='/api/payments', auth='Bearer', status='Chưa có',
         api_desc='Danh sách payment của customer kèm order_number.',
         when_call='payments_tab_page init.',
         ui_flow='List tile: loại Đặt cọc/Hoàn tiền, số tiền, trạng thái, ngày. Tap → detail.',
         after_success='Navigate /payments/:id.',
         repo='payments_repository.dart', screen='Tab Thanh toán', query='page; limit', body='', response='CustomerPayment[]', errors='401', priority='P1',
         dev_task=''),

    dict(stt=41, module='Thanh toán', be='BE-035', uc='UC-12', title='Chi tiết GD', method='GET', path='/api/payments/:id', auth='Bearer', status='Chưa có',
         api_desc='Chi tiết một payment: breakdown, trạng thái escrow, liên kết đơn.',
         when_call='Tap item trong tab Thanh toán.',
         ui_flow='payment_detail_page: header số tiền, timeline trạng thái, link “Xem đơn”.',
         after_success='—',
         repo='payments_repository.dart', screen='/payments/:paymentId', query='', body='', response='PaymentDetail', errors='404', priority='P1',
         dev_task=''),

    dict(stt=42, module='Thanh toán', be='BE-032', uc='UC-44', title='Hoàn tiền', method='POST', path='/api/payments/refund', auth='Bearer', status='Chưa có',
         api_desc='Hoàn % deposit khi hủy đơn — thường BE gọi nội bộ, app ít khi gọi trực tiếp.',
         when_call='Admin/auto từ cancel; app có thể chỉ hiển thị kết quả.',
         ui_flow='Sau hủy đơn — SnackBar “Hoàn 100%/50%”.',
         after_success='Refresh payments list.',
         repo='—', screen='—', query='', body='order_id; reason; percent?', response='refund', errors='400', priority='P2',
         dev_task=''),

    dict(stt=43, module='Chat đơn', be='BE-055', uc='UC-15', title='Inbox chat đơn', method='GET', path='/api/conversations', auth='Bearer', status='Chưa có',
         api_desc='Mỗi conversation gắn 1 order — preview tin cuối, unread.',
         when_call='Tab chat shortcut; build từ orders có conversation_id (hiện mock từ orders).',
         ui_flow='List avatar provider + order_number + last message + badge unread.\nTap → /chat/:id.\nKHÁC Pass đồ (không dùng buyer_id).',
         after_success='Open chat_thread_page.',
         repo='chat_repository.dart', screen='/chat; /home', query='', body='', response='Conversation[]', errors='401', priority='P1',
         dev_task='Tạo sau provider accept đơn (BE-054).'),

    dict(stt=44, module='Chat đơn', be='BE-055', uc='UC-15', title='Tin nhắn đơn', method='GET', path='/api/conversations/:id/messages', auth='Bearer', status='Chưa có',
         api_desc='Paginated messages PostgreSQL.',
         when_call='chat_thread_page init + scroll load more.',
         ui_flow='Bubble trái/phải theo sender_role customer/provider.\nKhông có is_deal_confirm.',
         after_success='ListView messages.',
         repo='chat_repository.dart', screen='/chat/:conversationId', query='page; limit', body='', response='Message[]', errors='403', priority='P1',
         dev_task=''),

    dict(stt=45, module='Chat đơn', be='BE-055', uc='UC-15', title='Gửi tin đơn', method='POST', path='/api/conversations/:id/messages', auth='Bearer', status='Chưa có',
         api_desc='Insert message text.',
         when_call='Bấm gửi trên chat_thread_page.',
         ui_flow='1) Nhập ô bottom.\n2) POST optimistic UI (optional).\n3) Append bubble.',
         after_success='Scroll to bottom.',
         repo='chat_repository.dart', screen='/chat/:conversationId', query='', body='content; message_type=text', response='Message', errors='403', priority='P1',
         dev_task=''),

    dict(stt=46, module='Thông báo', be='BE-056', uc='UC-16', title='DS thông báo', method='GET', path='/api/notifications', auth='Bearer', status='Chưa có',
         api_desc='Inbox promo + order_update + payment — action_data cho CTA.',
         when_call='messages_tab_page (tab Tin nhắn).',
         ui_flow='1) List promo_message_card.\n2) Tap → notification_detail hoặc deep link action_url.\n3) Filter type promotion vs order.',
         after_success='Navigate theo action_url.',
         repo='notifications_repository.dart', screen='Tab Tin nhắn', query='type; page; limit', body='', response='Notification[]', errors='401', priority='P1',
         dev_task=''),

    dict(stt=47, module='Thông báo', be='BE-056', uc='UC-16', title='Badge chưa đọc', method='GET', path='/api/notifications/unread-count', auth='Bearer', status='Chưa có',
         api_desc='Đếm notification is_read=false.',
         when_call='home_shell init + sau khi đọc notif.',
         ui_flow='Badge số trên tab Tin nhắn.',
         after_success='setState badge count.',
         repo='notifications_repository.dart', screen='home_shell', query='', body='', response='count', errors='401', priority='P1',
         dev_task=''),

    dict(stt=48, module='Thông báo', be='BE-057', uc='UC-16', title='Chi tiết TB', method='GET', path='/api/notifications/:id', auth='Bearer', status='Chưa có',
         api_desc='Chi tiết + mark read.',
         when_call='Tap notification item.',
         ui_flow='notification_detail_page: banner, body, nút CTA từ action_data.',
         after_success='Badge giảm.',
         repo='notifications_repository.dart', screen='notification_detail', query='', body='', response='Notification', errors='404', priority='P2',
         dev_task=''),

    dict(stt=49, module='Thông báo', be='BE-056', uc='UC-16', title='Mark read', method='PATCH', path='/api/notifications/:id/read', auth='Bearer', status='Chưa có',
         api_desc='Đánh dấu đã đọc không cần load full detail.',
         when_call='Swipe read hoặc khi mở list item.',
         ui_flow='Item mờ đi, badge cập nhật.',
         after_success='—',
         repo='notifications_repository.dart', screen='messages_tab', query='', body='{}', response='Notification', errors='404', priority='P2',
         dev_task=''),

    dict(stt=50, module='Thông báo', be='BE-058', uc='UC-58', title='FCM token', method='POST', path='/api/notifications/push-token', auth='Bearer', status='Chưa có',
         api_desc='Lưu device token để push order/message.',
         when_call='Sau login lần đầu / app resume.',
         ui_flow='Background — không UI.',
         after_success='—',
         repo='firebase messaging wrapper', screen='—', query='', body='token; platform', response='message', errors='401', priority='P2',
         dev_task=''),

    # --- Pass đồ ---
    dict(stt=51, module='Pass đồ', be='PASS-01', uc='UC-Pass', title='Khám phá tin', method='GET', path='/api/pass-items', auth='Bearer (tùy)', status='Chưa có — Mới',
         api_desc='Feed tin C2C: lọc keyword/category, phân trang. is_mine=false cho tin người khác.',
         when_call='pass_items_page tab Khám phá — init/search.',
         ui_flow='1) Grid/list card ảnh + giá + khu vực.\n2) Search bar → debounce GET.\n3) Tap card → /pass-items/:id.\n4) Không hiện nút sửa tin người khác.',
         after_success='Navigate detail.',
         repo='pass_item_repository.dart → fetchBrowse()', screen='/pass-items', query='keyword; category; page; limit', body='', response='PassItemPost[]', errors='401', priority='P1',
         dev_task='Thay mock _posts filter.'),

    dict(stt=52, module='Pass đồ', be='PASS-01', uc='UC-Pass', title='Tin của tôi', method='GET', path='/api/pass-items/mine', auth='Bearer', status='Chưa có — Mới',
         api_desc='Chỉ tin seller_id = current user.',
         when_call='pass_items_page tab Tin của tôi.',
         ui_flow='1) List tin của mình + trạng thái (Đang mở/Đã chốt/…).\n2) FAB Đăng tin → /pass-items/new.\n3) Tap → detail với panel seller.',
         after_success='Detail isMine=true.',
         repo='pass_item_repository.dart → fetchMine()', screen='/pass-items', query='page; limit', body='', response='PassItemPost[]', errors='401', priority='P1',
         dev_task=''),

    dict(stt=53, module='Pass đồ', be='PASS-01', uc='UC-Pass', title='Chi tiết tin', method='GET', path='/api/pass-items/:id', auth='Bearer', status='Chưa có — Mới',
         api_desc='Full tin + deal_confirmed, confirmed_price, buyer_transport_booked, interested_count.',
         when_call='pass_item_detail_page init.',
         ui_flow='BUYER: nút “Tôi muốn nhận”, chat, sau chốt → “Đặt xe lấy đồ” (nếu deal_confirmed).\nSELLER: section Người quan tâm, huỷ chốt (nếu sellerCanCancelDeal), vào chat từng khách.\nChưa chốt: buyer thấy “Chờ người bán chốt đơn”.',
         after_success='Render theo role isMine.',
         repo='pass_item_repository.dart → getById()', screen='/pass-items/:id', query='', body='', response='PassItemPost', errors='404', priority='P0',
         dev_task='Map deal_confirmed, buyer_transport_booked từ API.'),

    dict(stt=54, module='Pass đồ', be='PASS-02', uc='UC-Pass', title='Đăng tin', method='POST', path='/api/pass-items', auth='Bearer', status='Chưa có — Mới',
         api_desc='Tạo tin + trả listing_fee cần thanh toán.',
         when_call='create_pass_item_page — Đăng tin.',
         ui_flow='1) Form title, mô tả, category, condition, area, giá, ảnh.\n2) POST.\n3) Nếu requires_payment → dialog phí đăng tin → POST listing-fee/pay.\n4) OK → /pass-items mine.',
         after_success='SnackBar thành công; refresh mine tab.',
         repo='pass_item_repository.dart → create()', screen='/pass-items/new', query='', body='title; description; category; condition; area; price; image_url?; is_negotiable?', response='item; listing_fee', errors='422', priority='P0',
         dev_task='Upload ảnh trước qua POST /uploads.'),

    dict(stt=55, module='Pass đồ', be='PASS-03', uc='UC-Pass', title='Trả phí đăng tin', method='POST', path='/api/pass-items/:id/listing-fee/pay', auth='Bearer', status='Chưa có — Mới',
         api_desc='Thanh toán phí đăng tin qua PayOS.',
         when_call='Ngay sau tạo tin nếu listing_fee.requires_payment.',
         ui_flow='Dialog số tiền + rate_label → mở PayOS giống deposit.',
         after_success='Tin hiển thị công khai trên Khám phá.',
         repo='pass_item_repository.dart', screen='/pass-items/new', query='', body='payment_method: payos', response='payos URL/QR', errors='400', priority='P1',
         dev_task=''),

    dict(stt=56, module='Pass đồ', be='PASS-04', uc='UC-Pass', title='Đổi trạng thái tin', method='PATCH', path='/api/pass-items/:id/status', auth='Bearer Seller', status='Chưa có — Mới',
         api_desc='Seller đánh dấu reserved/completed/hidden.',
         when_call='Menu trên detail (ẩn tin, hoàn tất).',
         ui_flow='Chọn trạng thái → PATCH → chip cập nhật trên card.',
         after_success='Refresh detail.',
         repo='pass_item_repository.dart', screen='/pass-items/:id', query='', body='status', response='PassItemPost', errors='403', priority='P1',
         dev_task=''),

    dict(stt=57, module='Pass đồ', be='PASS-05', uc='UC-Pass', title='Quan tâm tin', method='POST', path='/api/pass-items/:id/interest', auth='Bearer Buyer', status='Chưa có — Mới',
         api_desc='Buyer đăng ký quan tâm — tăng interested_count, tạo thread chat.',
         when_call='pass_item_detail — nút “Tôi muốn nhận” (không phải seller).',
         ui_flow='1) Tap → POST.\n2) SnackBar “Đã gửi quan tâm”.\n3) Mở chat /pass-items/:id/chat (không query buyer = current user).\n4) Seller thấy buyer trong interested-buyers.',
         after_success='Navigate chat buyer; detail hiện đã quan tâm.',
         repo='pass_item_repository.dart → expressInterest()', screen='/pass-items/:id', query='', body='note?', response='interested; interested_count', errors='400 seller; 409', priority='P0',
         dev_task='Seed message đầu thread phía BE hoặc app.'),

    dict(stt=58, module='Pass đồ', be='PASS-06', uc='UC-Pass', title='DS khách quan tâm', method='GET', path='/api/pass-items/:id/interested-buyers', auth='Bearer Seller', status='Chưa có — Mới',
         api_desc='List buyer với preview tin nhắn, unread_for_seller.',
         when_call='pass_item_detail (seller) section Người quan tâm; pass_item_chat_page không có ?buyer= (seller inbox).',
         ui_flow='1) List PassInterestedBuyerTile.\n2) Badge unread.\n3) Tap → /pass-items/:id/chat?buyer={buyerId}.\n4) Seller KHÔNG chat chung 1 room — từng buyer một thread.',
         after_success='Open chat với query buyer.',
         repo='pass_item_repository.dart → interestedBuyers()', screen='/pass-items/:id; /pass-items/:id/chat', query='', body='', response='PassInterestedBuyer[]', errors='403', priority='P0',
         dev_task='pass_interested_buyer_tile.dart đã có UI.'),

    dict(stt=59, module='Pass đồ', be='PASS-07', uc='UC-Pass', title='Đọc chat Pass', method='GET', path='/api/pass-items/:id/chat/:buyerId/messages', auth='Bearer', status='Chưa có — Mới',
         api_desc='Thread messages; mark_read reset unread seller.',
         when_call='pass_item_chat_page init với query ?buyer= (seller) hoặc buyerId=me (buyer).',
         ui_flow='1) List bubble: from_buyer vs seller (map mine theo role).\n2) Bubble vàng is_deal_confirm / is_deal_cancel (hệ thống).\n3) Seller mở thread → mark_read=true.\n4) Offer bubble hiện offer_amount.',
         after_success='ListView + enable input.',
         repo='pass_item_repository.dart → fetchMessages()', screen='/pass-items/:id/chat?buyer=', query='mark_read=true', body='', response='PassChatMessage[]', errors='403', priority='P0',
         dev_task='Route app_router đã có query buyer.'),

    dict(stt=60, module='Pass đồ', be='PASS-07', uc='UC-Pass', title='Gửi chat Pass', method='POST', path='/api/pass-items/:id/chat/:buyerId/messages', auth='Bearer', status='Chưa có — Mới',
         api_desc='Gửi text hoặc offer; BE có thể không auto-reply (tắt mock).',
         when_call='Gửi ô chat; sheet “Đề nghị giá”.',
         ui_flow='1) Text → POST.\n2) Offer → is_offer=true, offer_amount.\n3) Không gửi deal confirm qua đây — dùng deal/confirm API.\n4) Optimistic append bubble.',
         after_success='Scroll bottom; cập nhật last_message trên buyer list.',
         repo='pass_item_repository.dart → sendMessage()', screen='/pass-items/:id/chat', query='', body='text; is_offer?; offer_amount?', response='PassChatMessage', errors='403', priority='P0',
         dev_task=''),

    dict(stt=61, module='Pass đồ', be='PASS-08', uc='UC-Pass', title='Chốt đơn', method='POST', path='/api/pass-items/:id/deal/confirm', auth='Bearer Seller', status='Chưa có — Mới',
         api_desc='deal_confirmed=true, status=reserved, system message trong thread.',
         when_call='pass_item_chat_page — seller menu “Chốt đơn” → nhập giá (optional).',
         ui_flow='1) Bottom sheet giá (để trống = giá đăng).\n2) POST confirm.\n3) SnackBar “Đã chốt — khách có thể đặt xe”.\n4) Thread thêm bubble is_deal_confirm.\n5) Buyer detail hiện nút Đặt xe lấy đồ.',
         after_success='Refresh messages + detail.',
         repo='pass_item_repository.dart → confirmDeal()', screen='chat: Chốt đơn', query='', body='agreed_price?', response='deal_confirmed; confirmed_price; status', errors='400; 403', priority='P0',
         dev_task='Lỗi nếu buyer_transport_booked.'),

    dict(stt=62, module='Pass đồ', be='PASS-09', uc='UC-Pass', title='Hủy chốt', method='POST', path='/api/pass-items/:id/deal/cancel', auth='Bearer Seller', status='Chưa có — Mới',
         api_desc='Revert deal nếu chưa transport_booked.',
         when_call='detail hoặc chat — “Huỷ chốt đơn” (chỉ khi sellerCanCancelDeal).',
         ui_flow='1) Nếu buyer_transport_booked → SnackBar không được huỷ.\n2) Confirm dialog.\n3) POST → bubble is_deal_cancel.\n4) Buyer mất nút đặt xe.',
         after_success='Refresh detail + chat.',
         repo='pass_item_repository.dart → cancelDealConfirmation()', screen='detail; chat', query='', body='', response='deal mở lại', errors='403', priority='P0',
         dev_task='sellerCanCancelDeal = dealConfirmed && !buyerTransportBooked.'),

    dict(stt=63, module='Pass đồ', be='PASS-10', uc='UC-Pass', title='Đã đặt xe', method='POST', path='/api/pass-items/:id/transport-booked', auth='Bearer Buyer', status='Chưa có — Mới',
         api_desc='buyer_transport_booked=true — khóa hủy chốt.',
         when_call='choose_location_page — Tiếp tục (luồng startPassItemDelivery).',
         ui_flow='1) Buyer đã chốt, bấm Đặt xe → booking location.\n2) Chọn destination, Tiếp tục → markTransportBooked TRƯỚC hoặc SAU create order (theo product: sau khi có order_id gửi kèm).\n3) Seller thấy “Khách đã đặt xe — không huỷ chốt”.',
         after_success='Tiếp packages/partners/payment với passItemId trong cubit.',
         repo='pass_item_repository.dart → markTransportBooked()', screen='/booking/location', query='', body='order_id?', response='buyer_transport_booked: true', errors='403', priority='P0',
         dev_task='choose_location_page đã gọi mock — đổi sang API.'),

    dict(stt=64, module='Pass đồ', be='PASS-11', uc='UC-Pass', title='Báo giá VC (optional)', method='GET', path='/api/pass-items/:id/transport-quotes', auth='Bearer', status='Chưa có — Mới',
         api_desc='Quick quotes vận chuyển — có thể bỏ, dùng providers/browse.',
         when_call='Optional trên pass detail.',
         ui_flow='Bottom sheet 2-3 quote card.',
         after_success='Chọn quote hoặc sang booking chuẩn.',
         repo='pass_item_repository.dart', screen='/pass-items/:id', query='', body='', response='TransportQuote[]', errors='404', priority='P2',
         dev_task=''),

    dict(stt=65, module='Upload', be='BE-060', uc='UC-62', title='Upload file', method='POST', path='/api/uploads', auth='Bearer', status='Chưa có',
         api_desc='Upload Storage trả public URL.',
         when_call='Trước POST pass-items (ảnh) hoặc avatar.',
         ui_flow='Picker → progress → nhận url gán vào form.',
         after_success='Set image_url field.',
         repo='upload helper', screen='create_pass_item; edit_profile', query='', body='multipart file; bucket', response='url; path', errors='413', priority='P1',
         dev_task=''),

    dict(stt=66, module='Giới thiệu', be='BE-060', uc='UC-62', title='Mã giới thiệu', method='GET', path='/api/referrals/me', auth='Bearer', status='Chưa có',
         api_desc='Mã referral sau review.',
         when_call='Sau review_trip_page submit thành công.',
         ui_flow='Bottom sheet chia sẻ mã + reward_amount.',
         after_success='Share sheet native.',
         repo='review flow', screen='sau /orders/:id/review', query='', body='', response='referral_code; reward_amount; share_message', errors='401', priority='P2',
         dev_task=''),
]
# fmt: on

# Luồng Pass đồ tổng hợp (sheet riêng trong cùng file)
PASS_FLOW = dict(
    stt='F1',
    module='LUỒNG NGHIỆP VỤ',
    be='PASS-ALL',
    uc='UC-Pass',
    title='Pass đồ — luồng end-to-end',
    method='—',
    path='(nhiều API)',
    auth='Bearer',
    status='—',
    api_desc='Marketplace C2C: chỉ người mua đặt xe; người bán chỉ chat + chốt giá. Sau chốt buyer đặt chuyển; seller không huỷ chốt nếu buyer đã book xe.',
    when_call='Toàn bộ feature /pass-items.',
    ui_flow='1) Khám phá GET /pass-items → detail.\n2) Buyer: POST interest → chat GET/POST .../chat/:buyerId/messages.\n3) Seller: GET interested-buyers → chat từng buyer.\n4) Seller: POST deal/confirm → buyer thấy Đặt xe.\n5) Buyer: BookingFlowCubit.startPassItemDelivery → /booking/location → POST transport-booked → POST /orders (pass_item_id) → deposit → tracking.\n6) Seller huỷ chốt: POST deal/cancel CHỈ khi chưa transport-booked.',
    after_success='—',
    repo='pass_item_repository + booking_flow_cubit',
    screen='/pass-items/* + /booking/*',
    query='',
    body='',
    response='',
    errors='',
    priority='P0',
    dev_task='Đọc pass_item_detail_page, pass_item_chat_page, choose_location_page trước khi nối API.',
)

BOOKING_FLOW = dict(
    stt='F2',
    module='LUỒNG NGHIỆP VỤ',
    be='BOOK-ALL',
    uc='UC-06–11',
    title='Đặt chuyến chuyển trọ — luồng end-to-end',
    method='—',
    path='(nhiều API)',
    auth='Bearer',
    status='—',
    api_desc='Chuyển trọ combo: địa điểm → validate-route → gói → nhà xe → bảo hiểm → estimate → tạo đơn → cọc → tracking → review.',
    when_call='Home CTA chuyển trọ hoặc Pass đồ Đặt xe.',
    ui_flow='1) /booking/location: recent-places + validate-route.\n2) /booking/packages: service-packages.\n3) /booking/partners: providers/browse.\n4) /booking/insurance: insurance-plans.\n5) /booking/payment: estimate-price, validate promo, POST orders, POST payments/deposit.\n6) /orders/:id/tracking: tracking + realtime.\n7) /orders/:id/review.',
    after_success='—',
    repo='booking_flow_cubit + customer_orders_repository',
    screen='/booking/*',
    query='',
    body='',
    response='',
    errors='',
    priority='P0',
    dev_task='State giữ toàn bộ trong BookingFlowCubit — map field sang POST /orders.',
)
